'use client';

import React, { useState } from 'react';
import { SwingActionPlan, RecommendationType } from '@/lib/types';
import { formatIDR } from '@/lib/idx-rules';
import {
  Target,
  ShieldAlert,
  Clock,
  Scale,
  Copy,
  Check,
  Zap,
  TrendingUp,
  AlertCircle,
} from 'lucide-react';

interface SwingPlanCardProps {
  ticker: string;
  name: string;
  currentPrice: number;
  recommendation: RecommendationType;
  setupTitle: string;
  confidenceScore: number;
  actionPlan: SwingActionPlan;
  isAIGenerated: boolean;
}

export default function SwingPlanCard({
  ticker,
  name,
  currentPrice,
  recommendation,
  setupTitle,
  confidenceScore,
  actionPlan,
  isAIGenerated,
}: SwingPlanCardProps) {
  const [copied, setCopied] = useState(false);

  const handleCopyPlan = () => {
    const text = `🎯 SWING TRADE PLAN: $${ticker} (${name})
Status: ${recommendation.replace(/_/g, ' ')}
Setup: ${setupTitle} (Score: ${confidenceScore}%)
Harga Sekarang: ${formatIDR(currentPrice)}
─────────────────────────
📍 Buy Zone: ${actionPlan.buyZone}
🎯 Target 1 (TP1): ${formatIDR(actionPlan.targetPrice1)} (+${actionPlan.potentialProfitPct}%)
🎯 Target 2 (TP2): ${formatIDR(actionPlan.targetPrice2)}
🛑 Cut Loss (SL): ${formatIDR(actionPlan.stopLoss)} (-${actionPlan.potentialRiskPct}%)
⚖️ Risk:Reward: ${actionPlan.riskRewardRatio}
⏱️ Time Horizon: ${actionPlan.estimatedHoldingPeriod}
Generated by IDX Swing Analyzer`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const getRecommendationBadge = () => {
    switch (recommendation) {
      case 'BUY_ON_BREAKOUT':
        return {
          label: 'BUY ON BREAKOUT',
          bg: 'bg-emerald-950/50 border-emerald-700/60 text-emerald-400',
          icon: TrendingUp,
        };
      case 'BUY_ON_WEAKNESS':
        return {
          label: 'BUY ON WEAKNESS',
          bg: 'bg-sky-950/50 border-sky-700/60 text-sky-400',
          icon: Zap,
        };
      case 'WAIT_AND_SEE':
        return {
          label: 'WAIT AND SEE',
          bg: 'bg-amber-950/50 border-amber-700/60 text-amber-300',
          icon: Clock,
        };
      case 'AVOID':
      default:
        return {
          label: 'AVOID / DOWNTREND',
          bg: 'bg-rose-950/50 border-rose-700/60 text-rose-400',
          icon: AlertCircle,
        };
    }
  };

  const badge = getRecommendationBadge();
  const BadgeIcon = badge.icon;

  return (
    <div className="bg-[#0e121d] border border-[#1c2438] rounded-lg p-4 flex flex-col justify-between h-full">
      <div>
        {/* Card Header */}
        <div className="flex flex-wrap items-center justify-between gap-2 pb-3 border-b border-[#182032]">
          <div className="flex items-center gap-2">
            <div
              className={`px-2.5 py-1 rounded border text-xs font-semibold tracking-wide flex items-center gap-1.5 ${badge.bg}`}
            >
              <BadgeIcon className="w-3.5 h-3.5" />
              <span>{badge.label}</span>
            </div>

            <div className="flex items-center gap-1 px-2 py-1 rounded bg-[#131826] text-[11px] font-medium text-slate-300 border border-[#20293d]">
              <span>Score: {confidenceScore}%</span>
              {isAIGenerated && (
                <span className="text-[10px] bg-emerald-950/60 text-emerald-400 border border-emerald-800/80 px-1 rounded ml-1 font-mono">
                  AI
                </span>
              )}
            </div>
          </div>

          {/* Copy Button */}
          <button
            onClick={handleCopyPlan}
            className="flex items-center gap-1.5 px-2.5 py-1 rounded bg-[#131826] hover:bg-[#182032] border border-[#20293d] text-xs font-medium text-slate-300 hover:text-white transition-colors"
          >
            {copied ? (
              <>
                <Check className="w-3 h-3 text-emerald-400" />
                <span className="text-emerald-400 text-[11px]">Tersalin</span>
              </>
            ) : (
              <>
                <Copy className="w-3 h-3 text-slate-400" />
                <span className="text-[11px]">Salin Plan</span>
              </>
            )}
          </button>
        </div>

        {/* Setup Title */}
        <div className="mt-3">
          <span className="text-[11px] text-slate-400 font-medium">Setup Swing:</span>
          <h3 className="text-sm font-semibold text-slate-100 mt-0.5">{setupTitle}</h3>
        </div>

        {/* Action Plan Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5 mt-3">
          {/* Buy Zone */}
          <div className="p-3 rounded-md bg-[#090c14] border border-[#192134]">
            <div className="flex items-center gap-1 text-[11px] text-sky-400 font-medium mb-0.5">
              <Zap className="w-3 h-3" />
              <span>Area Beli (Buy Zone)</span>
            </div>
            <div className="text-base font-bold font-mono text-white tabular-nums">
              {actionPlan.buyZone}
            </div>
            <div className="text-[10px] text-slate-400 mt-0.5">
              Entry: <span className="font-mono text-slate-200">{formatIDR(actionPlan.entryPrice)}</span>
            </div>
          </div>

          {/* Target Profits (TP1 & TP2) */}
          <div className="p-3 rounded-md bg-[#090c14] border border-[#192134]">
            <div className="flex items-center gap-1 text-[11px] text-emerald-400 font-medium mb-0.5">
              <Target className="w-3 h-3" />
              <span>Target Profit (TP)</span>
            </div>
            <div className="flex items-baseline justify-between">
              <span className="text-base font-bold font-mono text-emerald-400 tabular-nums">
                {formatIDR(actionPlan.targetPrice1)}
              </span>
              <span className="text-[10px] font-semibold text-emerald-400 bg-emerald-950/60 border border-emerald-800/80 px-1 rounded tabular-nums">
                +{actionPlan.potentialProfitPct}%
              </span>
            </div>
            <div className="text-[10px] text-slate-400 mt-0.5 flex justify-between">
              <span>TP2:</span>
              <span className="font-mono text-emerald-300 font-medium tabular-nums">
                {formatIDR(actionPlan.targetPrice2)}
              </span>
            </div>
          </div>

          {/* Stop Loss (Cut Loss) */}
          <div className="p-3 rounded-md bg-[#090c14] border border-[#192134]">
            <div className="flex items-center gap-1 text-[11px] text-rose-400 font-medium mb-0.5">
              <ShieldAlert className="w-3 h-3" />
              <span>Cut Loss (SL)</span>
            </div>
            <div className="flex items-baseline justify-between">
              <span className="text-base font-bold font-mono text-rose-400 tabular-nums">
                {formatIDR(actionPlan.stopLoss)}
              </span>
              <span className="text-[10px] font-semibold text-rose-400 bg-rose-950/60 border border-rose-800/80 px-1 rounded tabular-nums">
                -{actionPlan.potentialRiskPct}%
              </span>
            </div>
            <div className="text-[10px] text-slate-400 mt-0.5">Disiplin proteksi modal</div>
          </div>
        </div>
      </div>

      {/* Metrics Row: Risk/Reward & Holding Period */}
      <div className="grid grid-cols-2 gap-2 mt-3 pt-2.5 border-t border-[#182032] text-xs">
        <div className="flex items-center justify-between p-2 rounded bg-[#090c14] border border-[#192134]">
          <div className="flex items-center gap-1.5">
            <Scale className="w-3.5 h-3.5 text-amber-400" />
            <span className="text-[11px] text-slate-400">R:R Ratio</span>
          </div>
          <span className="font-mono font-bold text-slate-100 tabular-nums">
            {actionPlan.riskRewardRatio}
          </span>
        </div>

        <div className="flex items-center justify-between p-2 rounded bg-[#090c14] border border-[#192134]">
          <div className="flex items-center gap-1.5">
            <Clock className="w-3.5 h-3.5 text-sky-400" />
            <span className="text-[11px] text-slate-400">Timeframe</span>
          </div>
          <span className="font-mono text-slate-200 text-[11px]">
            {actionPlan.estimatedHoldingPeriod}
          </span>
        </div>
      </div>
    </div>
  );
}
