'use client';

import React, { useState } from 'react';
import { SwingActionPlan, RecommendationType } from '@/lib/types';
import { formatIDR } from '@/lib/idx-rules';
import {
  Target,
  ShieldAlert,
  Clock,
  Scale,
  Copy,
  Check,
  Zap,
  TrendingUp,
  AlertCircle,
  Sparkles,
} from 'lucide-react';

interface SwingPlanCardProps {
  ticker: string;
  name: string;
  currentPrice: number;
  recommendation: RecommendationType;
  setupTitle: string;
  confidenceScore: number;
  actionPlan: SwingActionPlan;
  isAIGenerated: boolean;
}

export default function SwingPlanCard({
  ticker,
  name,
  currentPrice,
  recommendation,
  setupTitle,
  confidenceScore,
  actionPlan,
  isAIGenerated,
}: SwingPlanCardProps) {
  const [copied, setCopied] = useState(false);

  const handleCopyPlan = () => {
    const text = `🎯 SWING TRADE PLAN: $${ticker} (${name})
Status: ${recommendation.replace(/_/g, ' ')}
Setup: ${setupTitle} (Score: ${confidenceScore}%)
Harga Sekarang: ${formatIDR(currentPrice)}
─────────────────────────
📍 Buy Zone: ${actionPlan.buyZone}
🎯 Target 1 (TP1): ${formatIDR(actionPlan.targetPrice1)} (+${actionPlan.potentialProfitPct}%)
🎯 Target 2 (TP2): ${formatIDR(actionPlan.targetPrice2)}
🛑 Cut Loss (SL): ${formatIDR(actionPlan.stopLoss)} (-${actionPlan.potentialRiskPct}%)
⚖️ Risk:Reward: ${actionPlan.riskRewardRatio}
⏱️ Time Horizon: ${actionPlan.estimatedHoldingPeriod}
Generated by IDX Swing Analyzer`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const getRecommendationBadge = () => {
    switch (recommendation) {
      case 'BUY_ON_BREAKOUT':
        return {
          label: 'BUY ON BREAKOUT',
          bg: 'bg-emerald-500/15 border-emerald-500/40 text-emerald-300 shadow-emerald-500/20',
          icon: TrendingUp,
        };
      case 'BUY_ON_WEAKNESS':
        return {
          label: 'BUY ON WEAKNESS',
          bg: 'bg-sky-500/15 border-sky-500/40 text-sky-300 shadow-sky-500/20',
          icon: Zap,
        };
      case 'WAIT_AND_SEE':
        return {
          label: 'WAIT AND SEE',
          bg: 'bg-amber-500/15 border-amber-500/40 text-amber-300 shadow-amber-500/20',
          icon: Clock,
        };
      case 'AVOID':
      default:
        return {
          label: 'AVOID / DOWNTREND',
          bg: 'bg-rose-500/15 border-rose-500/40 text-rose-300 shadow-rose-500/20',
          icon: AlertCircle,
        };
    }
  };

  const badge = getRecommendationBadge();
  const BadgeIcon = badge.icon;

  return (
    <div className="bg-gradient-to-b from-slate-900 via-slate-900/90 to-slate-950 border border-slate-800 rounded-2xl p-5 backdrop-blur-md shadow-2xl relative overflow-hidden">
      {/* Glow Effect */}
      <div className="absolute top-0 right-0 w-48 h-48 bg-sky-500/5 rounded-full blur-3xl pointer-events-none" />

      {/* Card Header */}
      <div className="flex flex-wrap items-center justify-between gap-3 pb-4 border-b border-slate-800">
        <div className="flex items-center gap-2.5">
          <div
            className={`px-3 py-1.5 rounded-xl border text-xs font-bold tracking-wide flex items-center gap-1.5 shadow-md ${badge.bg}`}
          >
            <BadgeIcon className="w-4 h-4" />
            <span>{badge.label}</span>
          </div>

          <div className="flex items-center gap-1 px-2.5 py-1 rounded-lg bg-slate-800 text-xs font-semibold text-slate-300 border border-slate-700">
            <Sparkles className="w-3.5 h-3.5 text-amber-400" />
            <span>Score: {confidenceScore}%</span>
            {isAIGenerated && (
              <span className="text-[10px] bg-emerald-500/20 text-emerald-300 px-1 rounded ml-1 font-mono">
                AI
              </span>
            )}
          </div>
        </div>

        {/* Copy Button */}
        <button
          onClick={handleCopyPlan}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-slate-800/80 hover:bg-slate-750 border border-slate-700 text-xs font-medium text-slate-300 hover:text-white transition-all shadow-sm"
        >
          {copied ? (
            <>
              <Check className="w-3.5 h-3.5 text-emerald-400" />
              <span className="text-emerald-400">Tersalin!</span>
            </>
          ) : (
            <>
              <Copy className="w-3.5 h-3.5 text-slate-400" />
              <span>Salin Trading Plan</span>
            </>
          )}
        </button>
      </div>

      {/* Setup Title */}
      <div className="mt-4">
        <span className="text-xs text-slate-400 font-medium">Swing Trading Setup:</span>
        <h3 className="text-base sm:text-lg font-bold text-white tracking-tight mt-0.5">
          {setupTitle}
        </h3>
      </div>

      {/* Action Plan Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mt-4">
        {/* Buy Zone */}
        <div className="p-4 rounded-xl bg-slate-950/70 border border-sky-900/40 relative overflow-hidden">
          <div className="flex items-center gap-1.5 text-xs text-sky-400 font-semibold mb-1">
            <Zap className="w-3.5 h-3.5" />
            <span>Area Beli (Buy Zone)</span>
          </div>
          <div className="text-lg font-extrabold font-mono text-white tracking-tight">
            {actionPlan.buyZone}
          </div>
          <div className="text-[11px] text-slate-400 mt-1">
            Entry ideal di sekitar {formatIDR(actionPlan.entryPrice)}
          </div>
        </div>

        {/* Target Profits (TP1 & TP2) */}
        <div className="p-4 rounded-xl bg-slate-950/70 border border-emerald-900/40">
          <div className="flex items-center gap-1.5 text-xs text-emerald-400 font-semibold mb-1">
            <Target className="w-3.5 h-3.5" />
            <span>Target Profit (TP)</span>
          </div>
          <div className="flex items-baseline justify-between">
            <span className="text-lg font-extrabold font-mono text-emerald-400">
              {formatIDR(actionPlan.targetPrice1)}
            </span>
            <span className="text-xs font-bold text-emerald-400 bg-emerald-500/10 px-1.5 py-0.5 rounded border border-emerald-500/20">
              +{actionPlan.potentialProfitPct}%
            </span>
          </div>
          <div className="text-[11px] text-slate-400 mt-1 flex justify-between">
            <span>TP 2 (Next Resistance):</span>
            <span className="font-mono text-emerald-300 font-semibold">
              {formatIDR(actionPlan.targetPrice2)}
            </span>
          </div>
        </div>

        {/* Stop Loss (Cut Loss) */}
        <div className="p-4 rounded-xl bg-slate-950/70 border border-rose-900/40">
          <div className="flex items-center gap-1.5 text-xs text-rose-400 font-semibold mb-1">
            <ShieldAlert className="w-3.5 h-3.5" />
            <span>Cut Loss (Stop Loss)</span>
          </div>
          <div className="flex items-baseline justify-between">
            <span className="text-lg font-extrabold font-mono text-rose-400">
              {formatIDR(actionPlan.stopLoss)}
            </span>
            <span className="text-xs font-bold text-rose-400 bg-rose-500/10 px-1.5 py-0.5 rounded border border-rose-500/20">
              -{actionPlan.potentialRiskPct}%
            </span>
          </div>
          <div className="text-[11px] text-slate-400 mt-1">
            Batas toleransi risiko swing
          </div>
        </div>
      </div>

      {/* Metrics Row: Risk/Reward & Holding Period */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-3 pt-3 border-t border-slate-800/80">
        <div className="flex items-center justify-between p-3 rounded-xl bg-slate-950/50 border border-slate-800">
          <div className="flex items-center gap-2">
            <Scale className="w-4 h-4 text-amber-400" />
            <div>
              <span className="text-xs text-slate-400 block font-medium">Risk-to-Reward Ratio</span>
              <span className="text-sm font-extrabold font-mono text-slate-100">
                {actionPlan.riskRewardRatio}
              </span>
            </div>
          </div>
          <span className="text-[11px] px-2 py-0.5 rounded-md bg-emerald-500/10 text-emerald-400 font-bold border border-emerald-500/20">
            Kriteria Sehat (&ge; 1:1.5)
          </span>
        </div>

        <div className="flex items-center justify-between p-3 rounded-xl bg-slate-950/50 border border-slate-800">
          <div className="flex items-center gap-2">
            <Clock className="w-4 h-4 text-sky-400" />
            <div>
              <span className="text-xs text-slate-400 block font-medium">Estimasi Holding Period</span>
              <span className="text-sm font-bold text-slate-100 font-mono">
                {actionPlan.estimatedHoldingPeriod}
              </span>
            </div>
          </div>
          <span className="text-[11px] text-slate-500">Swing Timeline</span>
        </div>
      </div>
    </div>
  );
}
