'use client';

import React, { useState } from 'react';
import { SwingActionPlan, RecommendationType } from '@/lib/types';
import { formatIDR } from '@/lib/idx-rules';
import {
  Target,
  ShieldAlert,
  Clock,
  Scale,
  Copy,
  Check,
  Zap,
  TrendingUp,
  AlertCircle,
  Sparkles,
} from 'lucide-react';

interface SwingPlanCardProps {
  ticker: string;
  name: string;
  currentPrice: number;
  recommendation: RecommendationType;
  setupTitle: string;
  confidenceScore: number;
  actionPlan: SwingActionPlan;
  isAIGenerated: boolean;
}

export default function SwingPlanCard({
  ticker,
  name,
  currentPrice,
  recommendation,
  setupTitle,
  confidenceScore,
  actionPlan,
  isAIGenerated,
}: SwingPlanCardProps) {
  const [copied, setCopied] = useState(false);

  const handleCopyPlan = () => {
    const text = `🎯 SWING TRADE PLAN: $${ticker} (${name})
Status: ${recommendation.replace(/_/g, ' ')}
Setup: ${setupTitle} (Score: ${confidenceScore}%)
Harga Sekarang: ${formatIDR(currentPrice)}
─────────────────────────
📍 Buy Zone: ${actionPlan.buyZone}
🎯 Target 1 (TP1): ${formatIDR(actionPlan.targetPrice1)} (+${actionPlan.potentialProfitPct}%)
🎯 Target 2 (TP2): ${formatIDR(actionPlan.targetPrice2)}
🛑 Cut Loss (SL): ${formatIDR(actionPlan.stopLoss)} (-${actionPlan.potentialRiskPct}%)
⚖️ Risk:Reward: ${actionPlan.riskRewardRatio}
⏱️ Time Horizon: ${actionPlan.estimatedHoldingPeriod}
Generated by IDX Swing Analyzer`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const getRecommendationBadge = () => {
    switch (recommendation) {
      case 'BUY_ON_BREAKOUT':
        return {
          label: 'BUY ON BREAKOUT',
          bg: 'bg-emerald-500/20 border-emerald-500/60 text-emerald-300',
          icon: TrendingUp,
        };
      case 'BUY_ON_WEAKNESS':
        return {
          label: 'BUY ON WEAKNESS',
          bg: 'bg-sky-500/20 border-sky-500/60 text-sky-300',
          icon: Zap,
        };
      case 'WAIT_AND_SEE':
        return {
          label: 'WAIT AND SEE',
          bg: 'bg-amber-500/20 border-amber-500/60 text-amber-300',
          icon: Clock,
        };
      case 'AVOID':
      default:
        return {
          label: 'AVOID / DOWNTREND',
          bg: 'bg-rose-500/20 border-rose-500/60 text-rose-300',
          icon: AlertCircle,
        };
    }
  };

  const badge = getRecommendationBadge();
  const BadgeIcon = badge.icon;

  return (
    <div className="bg-[#0b0f19] border border-[#162035] rounded-xl p-4 sm:p-5 flex flex-col justify-between h-full shadow-lg">
      <div>
        {/* Top Header: Recommendation, Score, AI tag, Copy */}
        <div className="flex flex-wrap items-center justify-between gap-2 pb-3.5 border-b border-[#141d30]">
          <div className="flex items-center gap-2">
            <div
              className={`px-3 py-1 rounded-lg border text-xs font-bold tracking-wide flex items-center gap-1.5 ${badge.bg}`}
            >
              <BadgeIcon className="w-3.5 h-3.5" />
              <span>{badge.label}</span>
            </div>

            <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-[#131b2e] text-xs font-bold text-slate-200 border border-[#1f2d4d]">
              <span>Score: {confidenceScore}%</span>
              {isAIGenerated && (
                <span className="flex items-center gap-0.5 text-[10px] bg-emerald-950/80 text-emerald-400 border border-emerald-800 px-1.5 py-0.2 rounded font-mono">
                  <Sparkles className="w-2.5 h-2.5" /> AI
                </span>
              )}
            </div>
          </div>

          <button
            onClick={handleCopyPlan}
            className="flex items-center gap-1.5 px-3 py-1 rounded-lg bg-[#131b2e] hover:bg-[#1a253e] border border-[#1f2d4d] text-xs font-medium text-slate-300 hover:text-white transition-colors"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-400" />
                <span className="text-emerald-400 text-xs">Tersalin!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5 text-slate-400" />
                <span>Salin Plan</span>
              </>
            )}
          </button>
        </div>

        {/* Setup Title Narrative */}
        <div className="mt-3.5">
          <span className="text-[11px] text-slate-400 font-medium">Setup Swing Trade:</span>
          <h3 className="text-sm sm:text-base font-bold text-slate-100 mt-0.5">{setupTitle}</h3>
        </div>

        {/* Large Action Rows (Figma Styled 4 Rows) */}
        <div className="space-y-2 mt-3.5">
          {/* Row 1: Buy Zone */}
          <div className="flex items-center justify-between p-3 rounded-lg bg-sky-950/20 border border-sky-900/40">
            <div className="flex items-center gap-2">
              <div className="w-7 h-7 rounded bg-sky-500/10 border border-sky-500/30 flex items-center justify-center">
                <Zap className="w-3.5 h-3.5 text-sky-400" />
              </div>
              <div>
                <span className="text-xs font-bold text-sky-300 block">Area Beli (Buy Zone)</span>
                <span className="text-[10px] text-slate-400">Entry: {formatIDR(actionPlan.entryPrice)}</span>
              </div>
            </div>
            <div className="text-right font-mono">
              <span className="text-base font-black text-white block tabular-nums">
                {actionPlan.buyZone}
              </span>
            </div>
          </div>

          {/* Row 2: Target Profit 1 */}
          <div className="flex items-center justify-between p-3 rounded-lg bg-emerald-950/20 border border-emerald-900/40">
            <div className="flex items-center gap-2">
              <div className="w-7 h-7 rounded bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center">
                <Target className="w-3.5 h-3.5 text-emerald-400" />
              </div>
              <div>
                <span className="text-xs font-bold text-emerald-300 block">Target Profit 1 (TP1)</span>
                <span className="text-[10px] text-slate-400">Target realistis resisten terdekat</span>
              </div>
            </div>
            <div className="text-right font-mono">
              <div className="flex items-center justify-end gap-1.5">
                <span className="text-base font-black text-emerald-400 tabular-nums">
                  {formatIDR(actionPlan.targetPrice1)}
                </span>
                <span className="text-[10px] font-bold text-emerald-300 bg-emerald-950/80 border border-emerald-800 px-1.5 py-0.5 rounded tabular-nums">
                  +{actionPlan.potentialProfitPct}%
                </span>
              </div>
            </div>
          </div>

          {/* Row 3: Target Profit 2 */}
          <div className="flex items-center justify-between p-2.5 rounded-lg bg-emerald-950/10 border border-emerald-900/20">
            <div className="flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-emerald-500 ml-2" />
              <div>
                <span className="text-xs font-semibold text-emerald-300/90 block">Target Profit 2 (TP2)</span>
                <span className="text-[10px] text-slate-400">Target ekspansi trend continuation</span>
              </div>
            </div>
            <div className="text-right font-mono">
              <span className="text-sm font-bold text-emerald-300 tabular-nums">
                {formatIDR(actionPlan.targetPrice2)}
              </span>
            </div>
          </div>

          {/* Row 4: Stop Loss */}
          <div className="flex items-center justify-between p-3 rounded-lg bg-rose-950/20 border border-rose-900/40">
            <div className="flex items-center gap-2">
              <div className="w-7 h-7 rounded bg-rose-500/10 border border-rose-500/30 flex items-center justify-center">
                <ShieldAlert className="w-3.5 h-3.5 text-rose-400" />
              </div>
              <div>
                <span className="text-xs font-bold text-rose-300 block">Cut Loss (Stop Loss)</span>
                <span className="text-[10px] text-slate-400">Batas toleransi breakdown support</span>
              </div>
            </div>
            <div className="text-right font-mono">
              <div className="flex items-center justify-end gap-1.5">
                <span className="text-base font-black text-rose-400 tabular-nums">
                  {formatIDR(actionPlan.stopLoss)}
                </span>
                <span className="text-[10px] font-bold text-rose-300 bg-rose-950/80 border border-rose-800 px-1.5 py-0.5 rounded tabular-nums">
                  -{actionPlan.potentialRiskPct}%
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Metrics Row: Risk/Reward & Holding Period */}
      <div className="grid grid-cols-2 gap-2.5 mt-3.5 pt-3 border-t border-[#141d30] text-xs">
        <div className="flex items-center justify-between p-2.5 rounded-lg bg-[#070a12] border border-[#131b2e]">
          <div className="flex items-center gap-1.5">
            <Scale className="w-3.5 h-3.5 text-amber-400" />
            <span className="text-slate-400 text-[11px] font-medium">Risk-to-Reward:</span>
          </div>
          <span className="font-mono font-black text-slate-100 text-sm tabular-nums">
            {actionPlan.riskRewardRatio}
          </span>
        </div>

        <div className="flex items-center justify-between p-2.5 rounded-lg bg-[#070a12] border border-[#131b2e]">
          <div className="flex items-center gap-1.5">
            <Clock className="w-3.5 h-3.5 text-sky-400" />
            <span className="text-slate-400 text-[11px] font-medium">Time Horizon:</span>
          </div>
          <span className="font-mono text-slate-200 text-xs font-semibold">
            {actionPlan.estimatedHoldingPeriod}
          </span>
        </div>
      </div>
    </div>
  );
}
